export const ADD_INNER_INGREDIENT_TO_CONSTRUCTOR: 'ADD_INNER_INGREDIENT_TO_CONSTRUCTOR' = 'ADD_INNER_INGREDIENT_TO_CONSTRUCTOR';
export const ADD_BUN_TO_CONSTRUCTOR: 'ADD_BUN_TO_CONSTRUCTOR' = 'ADD_BUN_TO_CONSTRUCTOR';
export const CHANGE_INNER_INGREDIENTS: 'CHANGE_INNER_INGREDIENTS' = 'CHANGE_INNER_INGREDIENTS';
export const REMOVE_BUN_FROM_CONSTRUCTOR: 'REMOVE_BUN_FROM_CONSTRUCTOR' = 'REMOVE_BUN_FROM_CONSTRUCTOR';

export const ADD_CURRENT_INGREDIENT: 'ADD_CURRENT_INGREDIENT' = 'ADD_CURRENT_INGREDIENT';
export const REMOVE_CURRENT_INGREDIENT = 'REMOVE_CURRENT_INGREDIENT';

export const GET_INGREDIENTS: 'GET_INGREDIENTS' = 'GET_INGREDIENTS';
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';

export const GET_ORDER_DETAILS: 'GET_ORDER_DETAILS' = 'GET_ORDER_DETAILS';
export const GET_ORDER_DETAILS_FAILED: 'GET_ORDER_DETAILS_FAILED' = 'GET_ORDER_DETAILS_FAILED';
export const GET_ORDER_DETAILS_SUCCESS: 'GET_ORDER_DETAILS_SUCCESS' = 'GET_ORDER_DETAILS_SUCCESS';
export const REMOVE_ORDER_DETAILS: 'REMOVE_ORDER_DETAILS' = 'REMOVE_ORDER_DETAILS';

export const INCREASE_INGREDIENT_COUNTER: 'INCREASE_INGREDIENT_COUNTER' = 'INCREASE_INGREDIENT_COUNTER';
export const DECREASE_INGREDIENT_COUNTER: 'DECREASE_INGREDIENT_COUNTER' = 'DECREASE_INGREDIENT_COUNTER';
export const CLEAR_INGREDIENT_COUNTER: 'CLEAR_INGREDIENT_COUNTER' = 'CLEAR_INGREDIENT_COUNTER';

export const REGISTER: 'REGISTER' = 'REGISTER';
export const REGISTER_FAILED: 'REGISTER_FAILED' = 'REGISTER_FAILED';
export const REGISTER_SUCCESS: 'REGISTER_SUCCESS' = 'REGISTER_SUCCESS';

export const LOGIN = 'LOGIN';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT: 'LOGOUT' = 'LOGOUT';
export const LOGOUT_FAILED: 'LOGOUT_FAILED' = 'LOGOUT_FAILED';
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS';

export const SEND_RESET_EMAIL: 'SEND_RESET_EMAIL' = 'SEND_RESET_EMAIL';
export const SEND_RESET_EMAIL_FAILED: 'SEND_RESET_EMAIL_FAILED' = 'SEND_RESET_EMAIL_FAILED';
export const SEND_RESET_EMAIL_SUCCESS: 'SEND_RESET_EMAIL_SUCCESS' = 'SEND_RESET_EMAIL_SUCCESS';

export const RESET_PASSWORD: 'RESET_PASSWORD' = 'RESET_PASSWORD';
export const RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED' = 'RESET_PASSWORD_FAILED';
export const RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS' = 'RESET_PASSWORD_SUCCESS';

export const GET_USER: 'GET_USER' = 'GET_USER';
export const GET_USER_FAILED: 'GET_USER_FAILED' = 'GET_USER_FAILED';
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';

export const PATCH_USER: 'PATCH_USER' = 'PATCH_USER';
export const PATCH_USER_FAILED: 'PATCH_USER_FAILED' = 'PATCH_USER_FAILED';
export const PATCH_USER_SUCCESS: 'PATCH_USER_SUCCESS' = 'PATCH_USER_SUCCESS';

export const ADD_RETURN_URL: 'ADD_RETURN_URL' = 'ADD_RETURN_URL';

export const WS_FEED_CONNECTION_START: 'WS_FEED_CONNECTION_START' = 'WS_FEED_CONNECTION_START';
export const WS_FEED_CONNECTION_SUCCESS: 'WS_FEED_CONNECTION_SUCCESS' = 'WS_FEED_CONNECTION_SUCCESS';
export const WS_FEED_CONNECTION_ERROR: 'WS_FEED_CONNECTION_ERROR' = 'WS_FEED_CONNECTION_ERROR';
export const WS_FEED_CONNECTION_CLOSED: 'WS_FEED_CONNECTION_CLOSED' = 'WS_FEED_CONNECTION_CLOSED';
export const WS_FEED_GET_MESSAGE: 'WS_FEED_GET_MESSAGE' = 'WS_FEED_GET_MESSAGE';

export const WS_ORDERS_CONNECTION_START: 'WS_ORDERS_CONNECTION_START' = 'WS_ORDERS_CONNECTION_START';
export const WS_ORDERS_CONNECTION_SUCCESS: 'WS_ORDERS_CONNECTION_SUCCESS' = 'WS_ORDERS_CONNECTION_SUCCESS';
export const WS_ORDERS_CONNECTION_ERROR: 'WS_ORDERS_CONNECTION_ERROR' = 'WS_ORDERS_CONNECTION_ERROR';
export const WS_ORDERS_CONNECTION_CLOSED: 'WS_ORDERS_CONNECTION_CLOSED' = 'WS_ORDERS_CONNECTION_CLOSED';
export const WS_ORDERS_GET_MESSAGE: 'WS_ORDERS_GET_MESSAGE' = 'WS_ORDERS_GET_MESSAGE';

export type TActionsType = {
    wsConnectionStart: typeof WS_FEED_CONNECTION_START | typeof WS_ORDERS_CONNECTION_START,
    wsConnectionSuccess: typeof WS_FEED_CONNECTION_SUCCESS | typeof WS_ORDERS_CONNECTION_SUCCESS,
    wsConnectionError: typeof WS_FEED_CONNECTION_ERROR | typeof WS_ORDERS_CONNECTION_ERROR,
    wsConnectionClosed: typeof WS_FEED_CONNECTION_CLOSED | typeof WS_ORDERS_CONNECTION_CLOSED,
    wsGetMessage: typeof WS_FEED_GET_MESSAGE | typeof WS_ORDERS_GET_MESSAGE
}

export const WsFeedActions: TActionsType = {
    wsConnectionStart: WS_FEED_CONNECTION_START,
    wsConnectionSuccess: WS_FEED_CONNECTION_SUCCESS,
    wsConnectionError: WS_FEED_CONNECTION_ERROR,
    wsConnectionClosed: WS_FEED_CONNECTION_CLOSED,
    wsGetMessage: WS_FEED_GET_MESSAGE
}

export const WsOrdersActions: TActionsType = {
    wsConnectionStart: WS_ORDERS_CONNECTION_START,
    wsConnectionSuccess: WS_ORDERS_CONNECTION_SUCCESS,
    wsConnectionError: WS_ORDERS_CONNECTION_ERROR,
    wsConnectionClosed: WS_ORDERS_CONNECTION_CLOSED,
    wsGetMessage: WS_ORDERS_GET_MESSAGE
}


