export const ADD_INNER_INGREDIENT_TO_CONSTRUCTOR = 'ADD_INNER_INGREDIENT_TO_CONSTRUCTOR';
export const ADD_BUN_TO_CONSTRUCTOR = 'ADD_BUN_TO_CONSTRUCTOR';
export const REMOVE_INNER_INGREDIENT_FROM_CONSTRUCTOR = 'REMOVE_INNER_INGREDIENT_FROM_CONSTRUCTOR';

export const ADD_CURRENT_INGREDIENT = 'ADD_CURRENT_INGREDIENT';
export const REMOVE_CURRENT_INGREDIENT = 'REMOVE_CURRENT_INGREDIENT';

export const ADD_ORDER_DETAILS = 'ADD_ORDER_DETAILS';
export const REMOVE_ORDER_DETAILS = 'REMOVE_ORDER_DETAILS';

export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';